name: gh-pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      

      - name: Build
        run: |
          sudo apt-get -y install build-essential libgl1-mesa-dev xvfb \
               automake libtool desktop-file-utils \
               ca-certificates autoconf libtool patchelf patch wget pkg-config \
               librsvg2-dev librsvg2-bin liblzma-dev \
               libxrender-dev libxcb-icccm4-dev \
               libxcb-keysyms1-dev libxcb-res0-dev \
               libxcb-image0 libx11-dev curl \
               libxcb-randr0-dev libxcb-xtest0-dev libxcb-xinerama0-dev \
               libxcb-shape0-dev libxcb-xkb-dev libxcb-render-util0 libxkbcommon-x11-dev

          ./scripts/make_repo.sh 
          python gensite.py

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./repositories
          cname: qt.antonyjr.in
